/* Generated by AN DISI Unibo */ 
package it.unibo.greetercontext
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "172.20.128.2", this, "greeterdocker.pl", "sysRules.pl"
	)
}

